# Machine Learning Emotion Detection

## 1. Load modules

In [34]:
import cv2 as cv
import numpy as np
from os import listdir, walk
from os.path import isfile, join

from pathlib import Path


from sklearn import tree


## 2. Load Images

In [2]:
def walk_through_dir(dir_path: Path) -> dict:
    """Prints dir_path content"""
    counts = dict()
    classes = dict()
    i=-1
    for dirpath, dirnames, filenames in walk(dir_path):
        i = i+1
        print(f"There are {len(dirnames)} directiories and {len(filenames)} images in '{dirpath}' folder ")
        if (i>0):
            c = dirpath.split('\\')
            counts[c[-1]] = len(filenames)
            classes[c[-1]] = i
    return (counts, classes)




In [ ]:
data_path = Path("Kaggle/CV/Emotions_detection")
images_path = data_path / "emotions_dataset"
train_path = images_path / "train"
test_path = images_path / "test"

ctrain, classes = walk_through_dir(train_path)
ctest, _ = walk_through_dir(test_path)

In [28]:
def make_datasets(counts, dataset_type, path, upscale = ""):
    x = []
    y = []

    for label, count in counts.items():
        for i in range(0, count):
            suffix = f"{dataset_type}/{label}/im{i}.png" if upscale == "" else f"{dataset_type}/{label}/im{i}_{upscale}.png"
            print(path / suffix)
            img = cv.imread(path / suffix)
            img = cv.cvtColor(img,cv.COLOR_BGR2GRAY)
            if type(img) is None:
                print("ALOOOOOOOO")
            x.append(img)
            y.append(label)

            # if i==0: 
            #     cv.imshow(mat=img, winname="asdfghjklasdfghjkl")
            #     cv.waitKey(0)
            #     cv.destroyAllWindows()
    x = np.array(x).astype(np.float32)
    x = x.reshape(x.shape[0], (x.shape[1]*x.shape[2]))
    return (x, y)


In [24]:

x_train, y_tr = make_datasets(ctrain, "train", images_path)
x_test, y_te = make_datasets(ctest, "test", images_path)



print(len(x_train))
print(len(x_test))


error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


In [36]:
print(classes)

def replace_label(y):
    y_new = [classes[label] for label in y]
    return np.array(y_new)

y_train = replace_label(y_tr)
y_test  = replace_label(y_te)

print(y_train)

{'angry': 1, 'disgusted': 2, 'fearful': 3, 'happy': 4, 'neutral': 5, 'sad': 6, 'surprised': 7}
[1. 1. 1. ... 7. 7. 7.]


In [37]:
x_train.shape

(28709, 2304)

#### Upscaled data

In [29]:
data_path = Path("upscaled_images")
images_path = data_path
train_path = images_path / "train"
test_path = images_path / "test"

ctrain, classes = walk_through_dir(train_path)
ctest, _ = walk_through_dir(test_path)

There are 7 directiories and 0 images in 'upscaled_images\train' folder 
There are 0 directiories and 3995 images in 'upscaled_images\train\angry' folder 
There are 0 directiories and 436 images in 'upscaled_images\train\disgusted' folder 
There are 0 directiories and 4097 images in 'upscaled_images\train\fearful' folder 
There are 0 directiories and 7215 images in 'upscaled_images\train\happy' folder 
There are 0 directiories and 4965 images in 'upscaled_images\train\neutral' folder 
There are 0 directiories and 4830 images in 'upscaled_images\train\sad' folder 
There are 0 directiories and 3171 images in 'upscaled_images\train\surprised' folder 
There are 7 directiories and 0 images in 'upscaled_images\test' folder 
There are 0 directiories and 958 images in 'upscaled_images\test\angry' folder 
There are 0 directiories and 111 images in 'upscaled_images\test\disgusted' folder 
There are 0 directiories and 1024 images in 'upscaled_images\test\fearful' folder 
There are 0 directiories 

In [30]:
x_train, y_tr = make_datasets(ctrain, "train", images_path, 4)
x_test, y_te = make_datasets(ctest, "test", images_path, 4)

print(len(x_train))
print(len(x_test))

print(classes)

def replace_label(y):
    y_new = [classes[label] for label in y]
    return np.array(y_new)

y_train = replace_label(y_tr)
y_test  = replace_label(y_te)

print(y_train)

upscaled_images\train\angry\im0_4.png
upscaled_images\train\angry\im1_4.png
upscaled_images\train\angry\im2_4.png
upscaled_images\train\angry\im3_4.png
upscaled_images\train\angry\im4_4.png
upscaled_images\train\angry\im5_4.png
upscaled_images\train\angry\im6_4.png
upscaled_images\train\angry\im7_4.png
upscaled_images\train\angry\im8_4.png
upscaled_images\train\angry\im9_4.png
upscaled_images\train\angry\im10_4.png
upscaled_images\train\angry\im11_4.png
upscaled_images\train\angry\im12_4.png
upscaled_images\train\angry\im13_4.png
upscaled_images\train\angry\im14_4.png
upscaled_images\train\angry\im15_4.png
upscaled_images\train\angry\im16_4.png
upscaled_images\train\angry\im17_4.png
upscaled_images\train\angry\im18_4.png
upscaled_images\train\angry\im19_4.png
upscaled_images\train\angry\im20_4.png
upscaled_images\train\angry\im21_4.png
upscaled_images\train\angry\im22_4.png
upscaled_images\train\angry\im23_4.png
upscaled_images\train\angry\im24_4.png
upscaled_images\train\angry\im25_4.

## KNN Classifier

In [52]:
knn = cv.ml.KNearest_create()
knn.train(x_train, cv.ml.ROW_SAMPLE, y_train)

123161.96712176094


In [53]:
ret,result,neighbours,dist = knn.findNearest(x_test,k=2)
 
# Now we check the accuracy of classification
# For that, compare the result with test_labels and check which are wrong



In [6]:
def calculate_accuracy(result, y_test):
    print(result)

    matches = 0

    for i in range(0, len(result)):
        if result[i] == y_test[i]:
            matches = matches + 1

    accuracy = matches*100.0/result.size
    print( accuracy )
    return accuracy

# calculate_accuracy(result, y_test)

## SGD classifier

In [7]:
from sklearn.linear_model import SGDClassifier

In [9]:
sgd = SGDClassifier(loss="hinge", penalty="elasticnet", max_iter=500)
sgd.fit(x_train, y_train)


SGDClassifier(max_iter=500, penalty='elasticnet')

In [10]:
prediction = sgd.predict(x_test)

In [69]:
prediction

array([3., 5., 6., ..., 5., 1., 7.], dtype=float32)

In [11]:
calculate_accuracy(prediction, y_test)

[3 5 1 ... 5 1 1]
26.316522708275286


26.316522708275286

In [70]:
calculate_accuracy(prediction, y_test)

[3. 5. 6. ... 5. 1. 7.]
30.21733073279465


30.21733073279465

## SVC

In [12]:
from sklearn import svm

svc = svm.SVC(decision_function_shape='ovo')
svc.fit(x_train, y_train)

KeyboardInterrupt: 

In [18]:
from sklearn import svm

svc = svm.SVC(decision_function_shape='ovo')
svc.fit(x_train, y_train)
svc_pred = svc.predict(x_test)

In [19]:
calculate_accuracy(svc_pred, y_test)

[3 6 4 ... 6 1 7]
44.69211479520758


44.69211479520758

In [73]:
calculate_accuracy(svc_pred, y_test)

[3. 6. 4. ... 6. 1. 7.]
44.69211479520758


44.69211479520758

## Naive Bayes

In [31]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
gnb_pred = gnb.fit(x_train, y_train).predict(x_test)

In [17]:
calculate_accuracy(gnb_pred, y_test)


[7 6 7 ... 6 7 7]
22.652549456673167


22.652549456673167

In [75]:
calculate_accuracy(gnb_pred, y_test)

[7. 6. 7. ... 6. 7. 7.]
22.652549456673167


22.652549456673167

## Decision Tree

In [76]:
from sklearn import tree
dt = tree.DecisionTreeClassifier()
dt = dt.fit(x_train, y_train)

dt_pred = dt.predict(x_test)

In [77]:
calculate_accuracy(dt_pred, y_test)


[4. 7. 1. ... 3. 7. 7.]
31.373641682920034


31.373641682920034

# Upscaled data

In [35]:
# svc = svm.SVC(decision_function_shape='ovo')
# svc.fit(x_train, y_train)
# svc_pred = svc.predict(x_test)

dt = tree.DecisionTreeClassifier()
dt = dt.fit(x_train, y_train)
dt_pred = dt.predict(x_test)

gnb = GaussianNB()
gnb = gnb.fit(x_train, y_train)
gnb_pred = gnb.predict(x_test)

sgd = SGDClassifier(loss="hinge", penalty="elasticnet", max_iter=500)
sgd.fit(x_train, y_train)
sgd_pred = sgd.predict(y_test)

In [ ]:
# calculate_accuracy(svc_pred, y_test)
calculate_accuracy(dt_pred, y_test)
calculate_accuracy(gnb_pred, y_test)
calculate_accuracy(sgd_pred, y_test)